         coverage:
  precision: 2
  round: down

  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      default:
        target: auto
        threshold: 0.1%
        informational: false
      unit:
        target: auto
        threshold: 0.1%
        informational: false
        flags:
          - unit
      integration:
        target: auto
        threshold: 0.1%
        informational: false
        flags:
          - integration
      acceptance:
        target: auto
        threshold: 0.1%
        informational: false
        flags:
          - acceptance
      core:
        target: auto
        threshold: 0.1%
        informational: false
        flags:
          - core
      common:
        target: auto
        threshold: 0.1%
        informational: false
        flags:
          - common
      support:
        target: auto
        threshold: 0.1%
        informational: false
        flags:
          - support
      api:
        target: auto
        threshold: 0.1%
        informational: false
        flags:
          - api
    patch:
      default:
        target: auto
        threshold: 0.1%
        informational: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

flags:
  core:
    paths:
      - selene/core/
  common:
    paths:
      - selene/common/
  support:
    paths:
      - selene/support/
  api:
    paths:
      - selene/api/
