coverage:
  precision: 2
  round: down

  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      default:
        off: true
      unit:
        target: auto
        threshold: 0.1%
        informational: true
        flags:
          - unit
    patch:
      default:
        target: auto
        threshold: 0.1%
        informational: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
