sudo: required
dist: trusty
language: python
python:
  - 3.6
  - 3.5
  - 2.7

addons:
  firefox: 46.0
  chrome: stable

cache: pip

before_install:
  - chmod +x .upload_reports.sh
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install: pip install -U tox-travis

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: tox

after_script: "./.upload_reports.sh"

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: yashaka
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: yashaka/selene
    python: 2.7
