server {
    listen 8000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /demo/tinymce;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
